# node-app / build . -> will look for the Dockerfile to run the build

# docker-compose build = docker build .
#    The one only builds the images, does not start the container.
# docker-compose up -d = docker run -d myimage
#    This one builds the images if the images do not exist and starts the containers.
# docker-compose up --build = docker build . & docker run myimage
#    This one forces the build even when not needed.
# docker-compose up --no-build
#    This one skips the image build process
# docker-compose down = docker stop and remove all containers created
# docker-compose stop = docker stop services
# docker-compose ps ~= docker ps
#    For the docker-compose.yml in the folder where the file exists

# restart policies per service/container
# "no" - never attempt to restart if container stops or crashes
#        has to be specified with quotes as 'no' because no is interpreted as boolean FALSE
# always - for any reason, attemp to restart
# on-failure - only restart if container stops with an error code
#              if 0 is passed, it will not be restart cause 0 is fine
#              0 - exited and everything is OK
#              1, 2, 3 etc - exited because something went wrong
# unless-stopped - restart unless we forcibly stop it

version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    restart: on-failure
    build: .
    ports:
      - "4001:8081"
